### ISSUE TITLE
Copy gist url does not respect github enterprise domain

### ISSUE THREAD

**Issue by KnisterPeter** [codespaces-contrib/gistpad#86] opened 2020-01-02 16:15 UTC
Right now its not possible to copy the url of the gist from the context menu if the extension is configured to github enterpise. The URL always build as a public gist URL.

It should be like this: `<host>/gist/<username>/<gist-id>`
(Not sure if this is always the case)

**Comment by lostintangent** [comment] 2020-01-02 16:19
Thanks for reporting this! I suspect there are a handful of other locations that are hard coding the public GitHub URL. I’ll fix all of these today 👍

**Comment by lostintangent** [comment] 2020-01-02 16:48
In the case of public GitHub, the URL is `https://gist.github.com/{userName}/{gistId}`. So it appears like in GitHub Enterprise, it's not just the domain that's different, but also that the path is pre-pended with `/gist`? Apologies for the stupid question, but I don't have a GHE account to actually test any of this :)

If you can confirm that for me (try it with and without the `/gist/` part), then I can make this change. It sounds like I likely need to replace the `Gistpad: Api Url` setting with a `GistPad: Host` setting, and then apply that to both the API URL as well as the gist URL.

BTW, one other question, have you already configured your GHE host with another extension? I just ask since I'd like to automatically pick this up if possible, to prevent users from needing to set their GHE host name twice.

**Comment by lostintangent** [comment] 2020-01-02 21:25
Other commands that need to be updated:

1. `View Profile on GitHub`
2. Pasting images into the editor
3. Git SSO
4. Relative paths in the playground webview

**Comment by KnisterPeter** [comment] 2020-01-03 08:24
> In the case of public GitHub, the URL is `https://gist.github.com/{userName}/{gistId}`. So it appears like in GitHub Enterprise, it's not just the domain that's different, but also that the path is pre-pended with `/gist`? 
> 
> If you can confirm that for me (try it with and without the `/gist/` part), then I can make this change. It sounds like I likely need to replace the `Gistpad: Api Url` setting with a `GistPad: Host` setting, and then apply that to both the API URL as well as the gist URL.
> 
The `/gist` part is indeed required. Without it I'll get a 404 as result.

> BTW, one other question, have you already configured your GHE host with another extension? I just ask since I'd like to automatically pick this up if possible, to prevent users from needing to set their GHE host name twice.
>
Kind of yes. There are a few extensions which require configuration of GHE. All a bit different.
I've maintaining `vscode-github`, the MS extension `github.vscode-pull-request-github` and yours at least are the ones that I know of.

**Comment by lostintangent** [comment] 2020-12-26 21:30
Closing this as a duplicate of #96, since GistPad no longer supports GitHub Enterprise after integrating with VS Code's native auth. We'll need to wait for VS Code to add that support, before GistPad can re-introduce it.

**Closed by lostintangent** 2020-12-26 21:30 UTC
Labels: area: ghe, bug
